/* MyGPI mobile app copy. Chrome deliberately mirrors the LIVE app's mixed language
   (English chrome, Georgian content) — do not "fix" to all-Georgian without the user. */

export const M = {
  hello: 'Hello',
  userName: 'Anna',
  points: '120 pts',
  tabs: { auto: 'Auto insurance', health: 'Health insurance' },
  /* V2 (three-tab nav): full labels can't fit 390px three-up — short forms only. */
  tabsV2: { auto: 'Auto', health: 'Health', curatio: 'კურაციო' },
  healthSection: 'HEALTH INSURANCE',
  newAppointment: 'NEW APPOINTMENT',
  curatio: {
    title: 'ჩემი კურაციო',
    full: 'სრულად',
    doctor: 'ექიმი',
    history: 'ისტორია',
    reminders: 'შეხსენებები',
    prevention: 'პრევენცია',
  },
  bookings: {
    title: 'ჯავშნები',
    all: 'ყველა',
    today: 'დღეს',
    clinic: 'კლინიკა',
    active: 'აქტიური',
    reschedule: 'გადაჯავშნა',
    cancel: 'გაუქმება',
    next: 'შემდეგი ჯავშანი',
    queueYour: 'თქვენი რიგი',
    queueWait: 'მოლოდინი',
    queueAhead: 'წინ',
    queuePatients: 'პაც.',
    queueLive: 'განახლდება რეალურ დროში',
    ticket: 'ბილეთის ნახვა',
    minutes: 'წთ',
  },
  referrals: {
    title: 'მიმართვები',
    all: 'ყველა',
    insured: 'დაზღვეული',
    number: 'მიმართვა:',
    inReview: 'განხილვაში',
    chronic: 'ქრონიკული',
    expiresIn: (d) => `ვადა იწურება ${d} დღეში`,
    renew: 'განახლება',
    request: 'მიმართვის მოთხოვნა +',
  },
  nav: ['main', 'policies', 'purchase', 'Payments', 'more'],
  demo: { normal: 'ჩვეულებრივი დღე', visit: 'ვიზიტის დღე', v1: 'ვერსია 1 · 2 ტაბი', v2: 'ვერსია 2 · 3 ტაბი' },
  /* V2 — Curatio tab dashboard + OTP gate for history-class data. */
  dash: {
    ticketLink: 'ბილეთი',
    protectedTitle: 'დაცული ინფორმაცია',
    protectedHint: 'სანახავად საჭიროა ერთჯერადი კოდი',
    unlockedNote: 'განბლოკილია ამ სესიისთვის',
    relock: 'ჩაკეტვა',
    lockedHistoryHint: 'ანალიზები · დანიშნულებები · ვიზიტები · დოკუმენტები',
    transferTitle: 'ისტორიის გადატანა · ექიმის დეტალები',
    lockedTransferHint: 'სხვა კლინიკიდან გადმოტანა · ექიმის სრული პროფილი',
  },
  /* V2 stakeholder-parity dashboard (mygpi_v3 source of truth). */
  dash2: {
    personAria: 'დაზღვეული პირი',
    close: 'დახურვა',
    todayVisit: 'დღეს ვიზიტი',
    hero: 'დღევანდელი ვიზიტი',
    heroTime: 'ჩაწერის დრო',
    heroLive: 'რიგი მიმდინარეობს',
    heroCta: 'ბილეთის ნახვა',
    queueTitle: 'გაიაქტიურე ციფრული რიგის ბილეთი',
    queueHint: 'აირჩიე ჯავშნებიდან',
    docInfo: 'სრული ინფო',
    historyTitle: 'ჩემი სამედიცინო ისტორია',
    historyHint: 'ანალიზები · დანიშნულებები · ვიზიტები · დოკუმენტები',
    preventionHint: 'ვაქცინაცია, სქრინინგი და სახ. პროგრამები',
    preventionBadge: '2 შეხს.',
  },
  /* A4 — personal doctor detail (F-03). Contact = WhatsApp only: in-app chat +
     "leave a message" are messaging (MVP2 out), phone-consult booking isn't in
     the spec. Booking CTA stays a dead end until F-04. */
  doc: {
    title: 'ჩემი პირადი ექიმი',
    onlineNow: 'Online · ხელმისაწვდომია ახლა',
    basicInfo: 'ძირითადი ინფორმაცია',
    clinic: 'კლინიკა',
    cabinet: 'კაბინეტი / სართული',
    workDays: 'სამუშაო დღეები',
    workHours: 'სამუშაო საათები',
    nextVisit: 'შემდეგი ვიზიტი',
    contact: 'დაკავშირება',
    whatsapp: 'WhatsApp',
    whatsappHint: 'პირდაპირი კონტაქტი',
    bookVisit: 'ჩაეწერე ვიზიტზე',
    transferTitle: 'სამედიცინო ისტორიის გადატანა',
    transferBody: 'გადაიტანე შენი სამედიცინო ისტორია სხვა ექიმთან კურაციოს ქსელში',
    transferCta: 'ექიმის არჩევა და გადატანა',
  },
  /* A7 — prevention screen (stakeholder sc-prev parity, scope-filtered). */
  prev: {
    title: 'პრევენცია',
    vaccines: 'ვაქცინაცია',
    screenings: 'სქრინინგ კვლევები',
    screeningsLink: 'სახ. პროგ. ›',
    screeningsHint: 'სახელმწიფო პროგრამებისა და ასაკობრივი ნორმების შესაბამისი პრევენციული კვლევები',
    book: 'ჩაეწერე',
    done: 'შესრულებულია',
  },
  /* A6c — V2 history hub (menu page between dash and section pages). */
  histhub: {
    title: 'სამედიცინო ისტორია',
    rows: {
      analyses: 'ანალიზები',
      prescriptions: 'დანიშნულებები',
      visits: 'ვიზიტები',
      docs: 'დოკუმენტები',
    },
    metaAnalyses: (n, last) => `${n} ჩანაწერი · ბოლო ${last}`,
    metaPrescriptions: 'მედიკამენტები · კვლევები · მიმართვები',
    metaVisits: (n) => `${n} ვიზიტი · 2025–2026`,
    metaDocs: (n) => `${n} ატვირთული ფაილი`,
    expiry: (n) => `${n} ვადა`,
  },
  /* A6 — V2 history parity (F-02/F-03; charts OUT — PDF only). */
  hist2: {
    sections: { meds: 'მედიკამენტები', studies: 'კვლევები', referrals: 'მიმართვები' },
    filterPeriod: 'პერიოდი',
    filterCat: 'კატეგორია',
    filterYear: 'წელი',
    medStates: { active: 'აქტიური', expiring: 'ვადა!', chronic: '♻ ქრონიკული' },
    renew: 'მოითხოვე განახლება',
    book: 'ჩაეწერე ექიმთან',
    refStatuses: { booked: 'შეკვეთილია', waiting: 'მოლოდინში' },
    years: ['2026', '2025', '2024'],
    yearRange: 'თარიღი',
    visitStatuses: { done: 'დასრულებული' },
    downloadPdf: 'ჩანაწერი PDF',
    uploadResult: 'შედეგის ატვირთვა',
    uploadTitle: 'გარე დოკუმენტის ატვირთვა',
    uploadHint: 'PDF, JPG, PNG · მაქს. 20MB',
    uploadCta: 'აირჩიე ფაილი',
    uploadedDocs: 'ატვირთული დოკუმენტები',
    sharedNote: 'გაზიარებულია ექიმთან',
    confid: 'კონფიდენციალურობა: ატვირთულ დოკუმენტებს ხედავს მხოლოდ პირადი ექიმი',
  },
  /* A5 — history transfer (F-03: doctor list + confirmation overlay). */
  transfer: {
    title: 'ისტორიის გადატანა',
    sub: 'აირჩიე ექიმი კურაციოს ქსელიდან',
    online: 'Online',
    tomorrow: 'ხვალ',
    includes: 'გადაიტანება: ვიზიტების ისტორია, ანალიზები, მიმართვები, მედიკამენტები',
    cancel: 'გაუქმება',
    confirm: 'დაადასტურე გადატანა',
    successTitle: 'გადატანა დადასტურდა',
    successBody: 'სამედიცინო ისტორია გადაეცა:',
    close: 'დახურვა',
  },
  /* A3 — digital queue-ticket activation (F-01). */
  qpick: {
    title: 'ციფრული ბილეთის გააქტიურება',
    today: 'დღეს',
    tomorrow: 'ხვალ',
    queueOpen: 'რიგი ღიაა',
    activate: 'გაიაქტიურე ბილეთი',
    lockedTomorrow: 'ბილეთი ხელმისაწვდომი იქნება ხვალ 09:00-ზე',
    lockedFuture: 'ბილეთი ხელმისაწვდომი იქნება ვიზიტის დღეს 09:00-ზე',
    empty: 'ახლო ჯავშნები არ არის',
    emptyHint: 'ბილეთის აღება შესაძლებელია ჯავშნის დღეს',
  },
  otp: {
    title: 'დაცული ინფორმაცია',
    body: 'სამედიცინო ჩანაწერების სანახავად შეიყვანე ერთჯერადი კოდი — გამოგზავნილია SMS-ით ნომერზე ***23',
    confirm: 'დადასტურება',
    resendIn: (s) => `ხელახლა გაგზავნა 0:${String(s).padStart(2, '0')}`,
    resend: 'ხელახლა გაგზავნა',
    close: 'დახურვა',
    demoNote: 'დემო: ნებისმიერი 4 ციფრი გამოდგება',
  },
  ticket: {
    title: 'ელექტრონული რიგი',
    yourTicket: 'თქვენი ბილეთი',
    wait: 'მოლოდინი',
    ahead: 'წინ',
    status: 'სტატუსი',
    live: 'ცოცხალი',
    map: 'რუკაზე ნახვა',
  },
  hub: {
    title: 'ჩემი კურაციო',
    allPersons: 'ყველა',
    todayStrip: (spec, time, num) => `${spec} · ${time} · რიგი ${num}`,
    doctorLabel: 'ჩემი პირადი ექიმი',
    online: 'Online',
    nextVisit: 'შემდეგი ვიზიტი:',
    book: 'ჯავშანი',
    details: 'დეტალები',
    historyTitle: 'სამედიცინო ისტორია',
    historyCounts: (c) => `ანალიზები ${c.analyses} · დანიშნ. ${c.prescriptions} · ვიზიტები ${c.visits} · დოკ. ${c.docs}`,
    remindersTitle: 'შეხსენებები',
    manage: 'მართვა',
    preventionTitle: 'პრევენცია',
    soon: 'მალე: ონლაინ კონსულტაცია · ექიმთან ჩატი',
  },
  history: {
    title: 'სამედიცინო ისტორია',
    tabs: { analyses: 'ანალიზები', prescriptions: 'დანიშნ.', visits: 'ვიზიტები', docs: 'დოკ.' },
    periods: { m3: '3 თვე', m6: '6 თვე', y1: '1 წელი', range: 'თარიღი' },
    statuses: { norm: 'ნორმა', warn: 'ყურადღება', crit: 'კრიტიკული', uploaded: 'ატვირთული' },
    upload: 'ატვირთე სხვა კლინიკის დოკუმენტი',
    download: 'ჩამოტვირთვა',
  },
}
