/* MyGPI mobile app copy. Chrome deliberately mirrors the LIVE app's mixed language
   (English chrome, Georgian content) — do not "fix" to all-Georgian without the user. */

export const M = {
  hello: 'Hello',
  userName: 'Anna',
  points: '120 pts',
  tabs: { auto: 'Auto insurance', health: 'Health insurance' },
  healthSection: 'HEALTH INSURANCE',
  newAppointment: 'NEW APPOINTMENT',
  curatio: {
    title: 'ჩემი კურაციო',
    full: 'სრულად',
    doctor: 'ექიმი',
    history: 'ისტორია',
    reminders: 'შეხსენებები',
    prevention: 'პრევენცია',
  },
  bookings: {
    title: 'ჯავშნები',
    all: 'ყველა',
    today: 'დღეს',
    clinic: 'კლინიკა',
    active: 'აქტიური',
    reschedule: 'გადაჯავშნა',
    cancel: 'გაუქმება',
    next: 'შემდეგი ჯავშანი',
    queueYour: 'თქვენი რიგი',
    queueWait: 'მოლოდინი',
    queueAhead: 'წინ',
    queuePatients: 'პაც.',
    queueLive: 'განახლდება რეალურ დროში',
    ticket: 'ბილეთის ნახვა',
    remindEarlier: 'შემახსენე 1 პაციენტით ადრე',
    minutes: 'წთ',
  },
  referrals: {
    title: 'მიმართვები',
    all: 'ყველა',
    insured: 'დაზღვეული',
    number: 'მიმართვა:',
    inReview: 'განხილვაში',
    chronic: 'ქრონიკული',
    expiresIn: (d) => `ვადა იწურება ${d} დღეში`,
    renew: 'განახლება',
    request: 'მიმართვის მოთხოვნა +',
  },
  nav: ['main', 'policies', 'purchase', 'Payments', 'more'],
  demo: { normal: 'ჩვეულებრივი დღე', visit: 'ვიზიტის დღე' },
  ticket: {
    title: 'ელექტრონული რიგი',
    yourTicket: 'თქვენი ბილეთი',
    wait: 'მოლოდინი',
    ahead: 'წინ',
    status: 'სტატუსი',
    live: 'ცოცხალი',
    map: 'რუკაზე ნახვა',
    remindTitle: 'შემახსენე 1 პაციენტით ადრე',
    remindSub: 'Push-შეტყობინება თქვენს რიგამდე',
  },
  hub: {
    title: 'ჩემი კურაციო',
    allPersons: 'ყველა',
    todayStrip: (spec, time, num) => `${spec} · ${time} · რიგი ${num}`,
    doctorLabel: 'ჩემი პირადი ექიმი',
    online: 'Online',
    nextVisit: 'შემდეგი ვიზიტი:',
    book: 'ჯავშანი',
    details: 'დეტალები',
    historyTitle: 'სამედიცინო ისტორია',
    historyCounts: (c) => `ანალიზები ${c.analyses} · დანიშნ. ${c.prescriptions} · ვიზიტები ${c.visits} · დოკ. ${c.docs}`,
    remindersTitle: 'შეხსენებები',
    manage: 'მართვა',
    preventionTitle: 'პრევენცია',
    soon: 'მალე: ონლაინ კონსულტაცია · ექიმთან ჩატი',
  },
  history: {
    title: 'სამედიცინო ისტორია',
    tabs: { analyses: 'ანალიზები', prescriptions: 'დანიშნ.', visits: 'ვიზიტები', docs: 'დოკ.' },
    periods: { m3: '3 თვე', m6: '6 თვე', y1: '1 წელი', range: 'თარიღი' },
    statuses: { norm: 'ნორმა', warn: 'ყურადღება', crit: 'კრიტიკული', uploaded: 'ატვირთული' },
    upload: 'ატვირთე სხვა კლინიკის დოკუმენტი',
    download: 'ჩამოტვირთვა',
  },
}
