#!/usr/bin/env python3
"""Regenerates src/assets/curatio-mark.svg — the Curatio mosaic mark.

Traced (NOT cropped) from the brand JPEG the client supplied,
"365419356_682381907263808_850007738978186289_n.jpg": 1000x1000, white lockup
on #424F9D.  Measured off that bitmap: the mark occupies x 106..357, y 374..625
(252 square) and is a strict 7x7 grid — column runs (106,139) (142,175) ...
(324,357), identical row runs — so pitch = 36.33 and each cell's bbox = 34.
32 of the 49 cells are inked; the four grid corners and a five-cell plus in the
middle are voids, which is what reads as a rosette around a diamond hole.

Cell geometry, from the cell's own width profile (width grows 2px per 1px of
height = true 45-degree sides, and extrapolates to zero 3.5px ABOVE the bbox):
a square rotated 45 degrees, virtual half-diagonal 20.5, corner radius 8.45 —
8.45*(sqrt(2)-1) = 3.5 is exactly the tip truncation, and the rounding pulls
the shape back to the measured 34px bbox.

Python, not .mjs like build-gpi-mark: this machine has no Node (see
CURATIO_MOBILE_BRIEF section 10).  Run:  python3 scripts/build-curatio-mark.py
"""
import math
import os
GRID = [
 "..XXX..",
 ".XXXXX.",
 "XXX.XXX",
 "XX...XX",
 "XXX.XXX",
 ".XXXXX.",
 "..XXX..",
]
P = 36.3333          # cell pitch (measured 106..357 / 7 cols)
C = 17.0             # first cell centre
RV = 20.5            # half-diagonal of the UNrounded diamond (virtual apex)
RR = 8.45            # corner radius  -> bbox half-diagonal lands on 17.0
def diamond(cx, cy):
    k = RR / math.sqrt(2)          # tangent offset projected on x and y
    V = [(0,-RV),(RV,0),(0,RV),(-RV,0)]
    pts = []
    for i in range(4):
        vx,vy = V[i]; nx,ny = V[(i+1)%4]
        ex,ey = (nx-vx), (ny-vy); L = math.hypot(ex,ey); ex,ey = ex/L, ey/L
        a = (vx+ex*RR, vy+ey*RR)   # leave this vertex
        b = (nx-ex*RR, ny-ey*RR)   # arrive at next vertex
        pts.append((a,b))
    d = []
    first = pts[0][0]
    d.append(f"M{cx+first[0]:.2f} {cy+first[1]:.2f}")
    for i in range(4):
        a,b = pts[i]
        d.append(f"L{cx+b[0]:.2f} {cy+b[1]:.2f}")
        na = pts[(i+1)%4][0]
        d.append(f"A{RR} {RR} 0 0 1 {cx+na[0]:.2f} {cy+na[1]:.2f}")
    d.append("Z")
    return "".join(d)
parts = []
for r, row in enumerate(GRID):
    for c, ch in enumerate(row):
        if ch == "X":
            parts.append(diamond(C + c * P, C + r * P))
path = "".join(parts)
assert path.count("M") == 32, path.count("M")

BLUE = "#424F9D"   # sampled off the supplied JPEG's ground (rgb 66,79,157)

HEADER = """GENERATED by scripts/build-curatio-mark.py \u2014 do not hand-edit.
   The CURATIO mosaic mark, traced (not cropped) from the brand JPEG the client
   supplied (1000x1000, white lockup on %s). The mark there is a strict 7x7 grid
   of rounded diamonds \u2014 pitch 36.33, cell bbox 34 \u2014 with 32 of the 49 cells
   inked: the four grid corners and a five-cell plus in the middle are voids,
   which is what reads as a rosette around a diamond-shaped hole. Rebuilt as
   vector because the artwork is raster and this lands in 16px slots.
   Cell geometry: a square rotated 45 degrees, virtual half-diagonal 20.5,
   corner radius 8.45 \u2014 8.45*(sqrt2-1) = the 3.5px tip truncation measured on
   the bitmap, and the rounding pulls the shape back to its 34px bbox.
   viewBox IS the mark's bbox, so the artwork bleeds to all four edges: pad in
   CSS, never in the file.""" % BLUE

here = os.path.dirname(__file__)

# 1) the asset of record \u2014 flat brand blue, for <img>, Figma and handoff.
svg = ('<?xml version="1.0" encoding="UTF-8"?>\n<!-- ' + HEADER + ' -->\n'
       '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 252 252" fill="%s" role="img">'
       '<path d="%s"/></svg>\n' % (BLUE, path))
svg_out = os.path.join(here, "..", "src", "assets", "curatio-mark.svg")
open(svg_out, "w").write(svg)

# 2) the inline component \u2014 same path, but currentColor, so a slot can tint it
#    (white on a coloured tile, brand blue when bare). Keeping both in ONE
#    generator is what stops the two copies from drifting apart.
jsx = ('/* ' + HEADER + '\n\n   Inline twin of src/assets/curatio-mark.svg: an <img> cannot inherit\n'
       '   currentColor, and this mark has to render white on a tile AND brand blue\n'
       '   bare in the switcher pill. Same path, one generator. */\n\n'
       'export const CURATIO_BLUE = \'%s\'\n\n'
       'export default function CuratioMark({ size = 16, className }) {\n'
       '  return (\n'
       '    <svg\n'
       '      width={size}\n'
       '      height={size}\n'
       '      viewBox="0 0 252 252"\n'
       '      fill="currentColor"\n'
       '      className={className}\n'
       '      aria-hidden="true"\n'
       '      focusable="false"\n'
       '    >\n'
       '      <path d="%s" />\n'
       '    </svg>\n'
       '  )\n'
       '}\n' % (BLUE, path))
jsx_out = os.path.join(here, "..", "src", "lib", "CuratioMark.jsx")
open(jsx_out, "w").write(jsx)

print("wrote", os.path.normpath(svg_out), len(svg), "bytes")
print("wrote", os.path.normpath(jsx_out), len(jsx), "bytes")
print(path.count("M"), "cells")

# 3) the perforation strip — a row of small brand diamonds (echo of the site's
#    title bands), white on transparent: consumers set colour context via opacity
#    or filter. Tile 28x12, two diamonds, repeat-x.
strip = ('<?xml version="1.0" encoding="UTF-8"?>\n'
         '<!-- GENERATED by scripts/build-curatio-mark.py \u2014 do not hand-edit. -->\n'
         '<svg xmlns="http://www.w3.org/2000/svg" width="28" height="12" viewBox="0 0 28 12">'
         '<g transform="translate(7,6)"><rect x="-3.4" y="-3.4" width="6.8" height="6.8" rx="1.9" transform="rotate(45)" fill="#ffffff"/></g>'
         '<g transform="translate(21,6)"><rect x="-3.4" y="-3.4" width="6.8" height="6.8" rx="1.9" transform="rotate(45)" fill="#ffffff"/></g>'
         '</svg>\n')
strip_out = os.path.join(here, "..", "src", "assets", "curatio-strip.svg")
open(strip_out, "w").write(strip)
print("wrote", os.path.normpath(strip_out), len(strip), "bytes")
