/* B2B CORPO portal strings — Georgian (ka). Kept separate from the My-Cabinet
   strings so the two platform contexts stay cleanly splittable (Rule 5). */

export const kaB2B = {
  topbar: {
    corpoTag: 'CORPO',
    client: 'შპს მაგალითი კომპანია',
    clientShort: 'მაგალითი კომპანია',
    clientMark: 'MK',
    // Per-client logo (production: each corporate account has its own). null → initials fallback.
    clientLogo: import.meta.env.BASE_URL + 'client-logo.svg',
    search: 'ძიება — პირი, პოლისი, ინვოისი…',
    searchClear: 'ძიების გასუფთავება',
    addInsured: 'დაზღვეულის დამატება',
    notifications: 'შეტყობინებები',
    home: 'GPI CORPO — მთავარ გვერდზე',
    user: 'გიორგი გვარიძე',
    role: 'ადმინი',
  },
  nav: {
    home: 'მთავარი',
    insured: 'დაზღვეულები',
    persons: 'პირები',
    vehicles: 'ავტომობილები',
    objects: 'ობიექტები',
    contracts: 'კონტრაქტები',
    requests: 'მოთხოვნები',
    claims: 'ზარალები',
    finances: 'ფინანსები',
    invoices: 'ინვოისები',
    statement: 'ამონაწერი',
    service: 'სერვისი',
    guide: 'გზამკვლევი',
    offers: 'შეთავაზებები',
    admin: 'ადმინისტრირება',
    adminUsers: 'მომხმარებლები და როლები',
    adminOrg: 'ორგანიზაცია',
    collapse: 'ჩაკეცვა',
    expand: 'გაშლა',
  },
  launcher: {
    open: 'სერვის-მენეჯერთან დაკავშირება',
    title: 'თქვენი სერვის-მენეჯერი',
    name: 'ნინო ნინოძე',
    phone: '2 505 111',
    phoneHref: 'tel:+995322505111',
    email: 'n.ninodze@gpih.ge',
  },
  crumbsLabel: 'გვერდის მდებარეობა',
  stub: {
    placeholder: 'გვერდის კონტენტი — შემდეგი ეტაპი',
    export: 'ექსპორტი',
  },
  contracts: {
    all: 'ყველა',
    filterLabel: 'პროდუქტის ფილტრი',
    cols: {
      number: 'კონტრაქტის №',
      product: 'პროდუქტი',
      start: 'დაწყება',
      end: 'დასრულება',
      insured: 'დაზღვეული',
      status: 'სტატუსი',
    },
    status: { active: 'აქტიური', preparing: 'მზადდება', ended: 'დასრულებული' },
    newContract: 'ახალი კონტრაქტი',
    actions: {
      menu: 'მოქმედებები',
      details: 'დეტალურად',
      deactivate: 'დეაქტივაცია',
      revoke: 'კონტრაქტის გაუქმება',
    },
    emptyTitle: 'ამ პროდუქტზე კონტრაქტი არ არის',
    emptyHint: 'სცადეთ სხვა ფილტრი ან იხილეთ ყველა კონტრაქტი',
    emptyAction: 'ყველას ჩვენება',
  },
  addIns: {
    title: 'დაზღვეულის დამატება',
    crumbParent: 'დაზღვეულები',
    crumbPersons: 'პირები',
    cancel: 'გაუქმება',
    cancelConfirm: 'შეყვანილი მონაცემები დაიკარგება. დატოვებთ გვერდს?',
    steps: { method: 'მეთოდი', data: 'მონაცემები', review: 'გადახედვა' },
    contractLabel: 'კონტრაქტი',
    contractChange: 'შეცვლა',
    contractSingle: 'ერთი აქტიური კონტრაქტი',
    method: {
      heading: 'როგორ გსურთ თანამშრომლების დამატება?',
      single: { title: 'ერთი პირის დამატება', meta: 'ფორმით — ოჯახის წევრებთან ერთად' },
      excel: { title: 'Excel ატვირთვა', meta: 'სტანდარტული შაბლონი · ვალიდაცია' },
      link: { title: 'ბმულის გაგზავნა', meta: 'თანამშრომლები თავად შეავსებენ ფორმას' },
      hr: { title: 'HR სისტემიდან', meta: 'BambooHR, API ინტეგრაცია' },
      later: 'მოგვიანებით',
      soon: 'მალე',
      headcount: 'გჭირდებათ ჯამური რაოდენობის შემოწმება?',
      headcountBody: 'შეადარეთ შემოსავლების სამსახურის მონაცემებს — დარწმუნდით, რომ არავინ გამოგრჩათ.',
    },
    who: {
      label: 'ვის ამატებთ?',
      employee: 'თანამშრომელი',
      employeeMeta: 'კომპანიის დასაქმებული',
      family: 'ოჯახის წევრი',
      familyMeta: 'თანამშრომელთან დაკავშირებული პირი',
    },
    form: {
      citizen: 'მოქალაქეობა',
      resident: 'საქართველოს მოქალაქე',
      nonresident: 'არარეზიდენტი',
      personalId: 'პირადი ნომერი',
      personalIdPh: 'მაგ. 01001001234',
      birthDate: 'დაბადების თარიღი',
      birthDatePh: 'დდ/თთ/წწწწ',
      found: 'მოიძებნა შემოსავლების სამსახურში',
      notFound: 'ამ მონაცემებით პირი ვერ მოიძებნა — შეავსეთ ველები ხელით.',
      firstName: 'სახელი',
      lastName: 'გვარი',
      gender: 'სქესი',
      genderPh: 'აირჩიეთ',
      male: 'მამრობითი',
      female: 'მდედრობითი',
      linkedTo: 'თანამშრომელი (ბმა)',
      linkedToPh: 'აირჩიეთ თანამშრომელი',
      linkedNew: 'ახალი:',
      relation: 'კავშირი',
      relationPh: 'აირჩიეთ კავშირი',
      mobile: 'მობილური',
      mobilePh: '+995 5XX XXX XXX',
      email: 'ელ-ფოსტა',
      emailPh: 'name@mail.ge',
      address: 'მისამართი',
      addressPh: 'ქ. თბილისი, ...',
      package: 'სადაზღვევო პაკეტი',
      packagePh: 'აირჩიეთ პაკეტი',
      policyType: 'პოლისის ტიპი',
      premium: 'ყოველთვიური პრემია',
      systemTag: 'სისტემიდან',
      policyTypeValue: 'ჯანმრთ. CORPO Standard',
      addToList: 'სიაში დამატება',
      updateInList: 'განახლება',
      clearForm: 'გასუფთავება',
      errRequired: 'სავალდებულო ველი',
      errPid: 'პირადი ნომერი უნდა შედგებოდეს 11 ციფრისგან.',
    },
    batch: {
      heading: 'სიაშია',
      empty: 'ჯერ არავინ დაგიმატებიათ — შეავსეთ ფორმა და დაამატეთ სიაში.',
      addFamily: 'ოჯახის წევრი',
      edit: 'რედაქტირება',
      remove: 'წაშლა',
      employeeTag: 'თანამშრომელი',
      perMonth: '₾/თვე',
    },
    side: {
      rulesTitle: 'კონტრაქტის წესები',
      rulesAuto: 'აქტიურდება ავტომატურად',
      ruleWindowTitle: 'დამატების ფანჯარა',
      ruleWindow: 'ყოველი თვის 1–25 რიცხვი',
      rulePackageTitle: 'პაკეტი',
      rulePackage: 'კონტრაქტიდან 3 თვის შემდეგ ახალი პირისთვის — მხოლოდ „ბაზისი"',
      ruleWaitTitle: 'ლოდინის პერიოდი',
      ruleWait: 'ორსულობა / მშობიარობა — 9 თვე',
      nextTitle: 'რა მოხდება შემდეგ',
      nextBody: 'ავტო-ვალიდაცია → GPI ბექ-ოფისი (≤ 24 სთ) → შეტყობინება',
      bulkTip: '10+ პირის დამატება? გამოიყენეთ Excel ან ბმული — მე-1 ნაბიჯზე.',
    },
    review: {
      heading: 'გადახედეთ და გააგზავნეთ',
      people: 'პირი',
      total: 'ჯამი',
      totalNote: 'დაემატება მომდევნო ინვოისს',
      submit: 'მოთხოვნის გაგზავნა',
    },
    done: {
      title: 'მოთხოვნა შეიქმნა',
      requestNo: 'მოთხოვნა #43512',
      status: 'დამუშავების პროცესში',
      meta: 'პასუხი ≤ 24 საათში — მიიღებთ შეტყობინებას',
      viewRequest: 'მოთხოვნის ნახვა',
      addMore: 'კიდევ დამატება',
      home: 'მთავარი გვერდი',
    },
  },
  pages: {
    home: { title: 'მთავარი გვერდი', subtitle: 'მიმოხილვა და შეხსენებები' },
    persons: { title: 'პირები', subtitle: '1,942 დაზღვეული პირი · 198 პოლისი' },
    vehicles: { title: 'ავტომობილები', subtitle: '34 დაზღვეული ავტომობილი · CASCO' },
    objects: { title: 'ობიექტები', subtitle: '16 დაზღვეული ობიექტი · ქონება' },
    contracts: { title: 'კონტრაქტები', subtitle: '12 კონტრაქტი · 6 პროდუქტი' },
    requests: { title: 'მოთხოვნები', subtitle: '7 მიმდინარე მოთხოვნა' },
    claims: { title: 'ზარალები', subtitle: '3 ელოდება თქვენს დადასტურებას' },
    invoices: { title: 'ინვოისები', subtitle: '1 ვადაგადაცილებული · ₾ 6,450' },
    statement: { title: 'ამონაწერი', subtitle: 'პრემიის განაწილება — კომპანია / თანამშრომელი' },
    guide: { title: 'გზამკვლევი', subtitle: 'ვიდეოები, FAQ და სახელმძღვანელოები თანამშრომლებისთვის' },
    offers: { title: 'შეთავაზებები', subtitle: 'შეთავაზებები კომპანიისა და თანამშრომლებისთვის' },
    adminUsers: { title: 'მომხმარებლები და როლები', subtitle: 'წვდომის მართვა' },
    adminOrg: { title: 'ორგანიზაცია', subtitle: 'კომპანიის მონაცემები' },
  },
}
