/* B2B CORPO portal strings — Georgian (ka). Kept separate from the My-Cabinet
   strings so the two platform contexts stay cleanly splittable (Rule 5). */

export const kaB2B = {
  topbar: {
    corpoTag: 'CORPO',
    client: 'შპს მაგალითი კომპანია',
    clientShort: 'მაგალითი კომპანია',
    clientMark: 'MK',
    // Per-client logo (production: each corporate account has its own). null → initials fallback.
    clientLogo: import.meta.env.BASE_URL + 'client-logo.svg',
    search: 'ძიება — პირი, პოლისი, ინვოისი…',
    searchClear: 'ძიების გასუფთავება',
    newRequest: 'ახალი მოთხოვნა',
    notifications: 'შეტყობინებები',
    home: 'GPI CORPO — მთავარ გვერდზე',
    user: 'გიორგი გვარიძე',
    role: 'ადმინი',
  },
  nav: {
    home: 'მთავარი',
    insured: 'დაზღვეულები',
    persons: 'პირები',
    vehicles: 'ავტომობილები',
    objects: 'ობიექტები',
    contracts: 'კონტრაქტები',
    requests: 'მოთხოვნები',
    claims: 'ზარალები',
    finances: 'ფინანსები',
    invoices: 'ინვოისები',
    statement: 'ამონაწერი',
    service: 'სერვისი',
    guide: 'გზამკვლევი',
    offers: 'შეთავაზებები',
    admin: 'ადმინისტრირება',
    adminUsers: 'მომხმარებლები და როლები',
    adminOrg: 'ორგანიზაცია',
    collapse: 'ჩაკეცვა',
    expand: 'გაშლა',
  },
  launcher: {
    open: 'სერვის-მენეჯერთან დაკავშირება',
    title: 'თქვენი სერვის-მენეჯერი',
    name: 'ნინო ნინოძე',
    phone: '2 505 111',
    phoneHref: 'tel:+995322505111',
    email: 'n.ninodze@gpih.ge',
  },
  crumbsLabel: 'გვერდის მდებარეობა',
  stub: {
    placeholder: 'გვერდის კონტენტი — შემდეგი ეტაპი',
    export: 'ექსპორტი',
  },
  contracts: {
    all: 'ყველა',
    filterLabel: 'პროდუქტის ფილტრი',
    cols: {
      number: 'კონტრაქტის №',
      product: 'პროდუქტი',
      start: 'დაწყება',
      end: 'დასრულება',
      insured: 'დაზღვეული',
      status: 'სტატუსი',
    },
    status: { active: 'აქტიური', preparing: 'მზადდება', ended: 'დასრულებული' },
    newContract: 'ახალი კონტრაქტი',
    actions: {
      menu: 'მოქმედებები',
      details: 'დეტალურად',
      deactivate: 'დეაქტივაცია',
      revoke: 'კონტრაქტის გაუქმება',
    },
    emptyTitle: 'ამ პროდუქტზე კონტრაქტი არ არის',
    emptyHint: 'სცადეთ სხვა ფილტრი ან იხილეთ ყველა კონტრაქტი',
    emptyAction: 'ყველას ჩვენება',
  },
  pages: {
    home: { title: 'მთავარი გვერდი', subtitle: 'მიმოხილვა და შეხსენებები' },
    persons: { title: 'პირები', subtitle: '1,942 დაზღვეული პირი · 198 პოლისი' },
    vehicles: { title: 'ავტომობილები', subtitle: '34 დაზღვეული ავტომობილი · CASCO' },
    objects: { title: 'ობიექტები', subtitle: '16 დაზღვეული ობიექტი · ქონება' },
    contracts: { title: 'კონტრაქტები', subtitle: '12 კონტრაქტი · 6 პროდუქტი' },
    requests: { title: 'მოთხოვნები', subtitle: '7 მიმდინარე მოთხოვნა' },
    claims: { title: 'ზარალები', subtitle: '3 ელოდება თქვენს დადასტურებას' },
    invoices: { title: 'ინვოისები', subtitle: '1 ვადაგადაცილებული · ₾ 6,450' },
    statement: { title: 'ამონაწერი', subtitle: 'პრემიის განაწილება — კომპანია / თანამშრომელი' },
    guide: { title: 'გზამკვლევი', subtitle: 'ვიდეოები, FAQ და სახელმძღვანელოები თანამშრომლებისთვის' },
    offers: { title: 'შეთავაზებები', subtitle: 'შეთავაზებები კომპანიისა და თანამშრომლებისთვის' },
    adminUsers: { title: 'მომხმარებლები და როლები', subtitle: 'წვდომის მართვა' },
    adminOrg: { title: 'ორგანიზაცია', subtitle: 'კომპანიის მონაცემები' },
  },
}
