/* B2B CORPO portal strings — Georgian (ka). Kept separate from the My-Cabinet
   strings so the two platform contexts stay cleanly splittable (Rule 5). */
import { ASSETS } from '../lib/assets.js'

export const kaB2B = {
  topbar: {
    corpoTag: 'CORPO',
    client: 'შპს მაგალითი კომპანია',
    clientShort: 'მაგალითი კომპანია',
    clientMark: 'MK',
    // Per-client logo (production: each corporate account has its own). null → initials fallback.
    clientLogo: ASSETS.clientLogo,
    search: 'ძიება — პირი, პოლისი, ინვოისი…',
    searchClear: 'ძიების გასუფთავება',
    addInsured: 'დაზღვეულის დამატება',
    notifications: 'შეტყობინებები',
    home: 'GPI CORPO — მთავარ გვერდზე',
    user: 'გიორგი გვარიძე',
    role: 'ადმინი',
  },
  nav: {
    home: 'მთავარი',
    policies: 'პოლისები',
    contracts: 'კონტრაქტები',
    requests: 'მოთხოვნები',
    claims: 'ზარალები',
    finances: 'ფინანსები',
    invoices: 'ინვოისები',
    statement: 'ამონაწერი',
    service: 'სერვისი',
    guide: 'გზამკვლევი',
    offers: 'შეთავაზებები',
    admin: 'ადმინისტრირება',
    adminUsers: 'მომხმარებლები და როლები',
    adminOrg: 'ორგანიზაცია',
    collapse: 'ჩაკეცვა',
    expand: 'გაშლა',
  },
  launcher: {
    open: 'სერვის-მენეჯერთან დაკავშირება',
    title: 'თქვენი სერვის-მენეჯერი',
    name: 'ნინო ნინოძე',
    phone: '2 505 111',
    phoneHref: 'tel:+995322505111',
    email: 'n.ninodze@gpih.ge',
  },
  crumbsLabel: 'გვერდის მდებარეობა',
  stub: {
    placeholder: 'გვერდის კონტენტი — შემდეგი ეტაპი',
    export: 'ექსპორტი',
  },
  /* Filter Bar / Filter Popover — the common table-toolbar pattern (2026-07-15).
     Shared by every B2B table; component takes all text via this block. */
  filterBar: {
    filter: 'ფილტრი',
    apply: 'გაფილტვრა',
    clear: 'გასუფთავება',
    results: (n) => `${n} შედეგი`,
    export: 'CSV ექსპორტი',
    appliedLabel: 'აქტიური ფილტრები',
    remove: 'მოხსნა',
    rangeFrom: 'თარიღიდან',
    rangeTo: 'თარიღამდე',
    datePlaceholder: 'დდ.თთ.წწწწ',
    prevMonth: 'წინა თვე',
    nextMonth: 'შემდეგი თვე',
    /* generic date presets — shared by every range filter */
    presets: {
      last3m: 'ბოლო 3 თვე',
      last6m: 'ბოლო 6 თვე',
      last12m: 'ბოლო 12 თვე',
      thisYear: 'მიმდინარე წელი',
      lastYear: 'გასული წელი',
    },
  },
  /* Customize-table dialog — shared by every Data Table (2026-07-16) */
  tableCustomize: {
    title: 'ცხრილის მორგება',
    save: 'შენახვა',
    cancel: 'გაუქმება',
    always: 'ყოველთვის ჩანს',
    move: 'გადაადგილება',
  },
  policies: {
    subtitle: (n, p) => `${n} პოლისი · ${p} პროდუქტი`,
    addPolicy: 'პოლისის დამატება',
    tabsLabel: 'პროდუქტი',
    status: { active: 'აქტიური', ended: 'დასრულებული', canceled: 'გაუქმებული' },
    relation: { employee: 'თანამშრომელი', spouse: 'მეუღლე', child: 'შვილი', parent: 'მშობელი' },
    familyGroup: 'ოჯახის წევრი',
    perMonth: '/ თვე',
    filterCats: {
      status: 'სტატუსი',
      contract: 'კონტრაქტი',
      package: 'პაკეტი',
      relation: 'კავშირი',
      period: 'პერიოდი',
      type: 'ტიპი',
    },
    cols: {
      insured: 'დაზღვეული',
      person: 'სახელი გვარი',
      pid: 'პირადი №',
      relation: 'კავშირი',
      package: 'პაკეტი',
      premium: 'პრემია',
      contract: 'კონტრაქტი №',
      policy: 'პოლისი №',
      start: 'დაწყება',
      end: 'დასრულება',
      status: 'სტატუსი',
      plate: 'სახ. ნომერი',
      vehicle: 'ავტომობილი',
      owner: 'მფლობელი',
      period: 'პერიოდი',
      object: 'ობიექტი',
      type: 'ტიპი',
      sum: 'სად. თანხა',
    },
    search: {
      health: 'ძიება — სახელი, პირადი № ან პოლისი',
      auto: 'ძიება — ნომერი, მოდელი ან მფლობელი',
      travel: 'ძიება — სახელი, პირადი № ან პოლისი',
      property: 'ძიება — მისამართი ან პოლისი',
    },
    actions: {
      menu: 'მოქმედებები',
      details: 'დეტალურად',
      pdf: 'PDF-ის გაგზავნა',
      cancel: 'პოლისის გაუქმება',
    },
    emptyTitle: 'პოლისი ვერ მოიძებნა',
    emptyHint: 'შეცვალეთ ან გაასუფთავეთ ფილტრები და ძიება',
    emptyAction: 'ყველას ჩვენება',
  },
  contracts: {
    all: 'ყველა',
    subtitle: (n, p) => `${n} კონტრაქტი · ${p} პროდუქტი`,
    searchPlaceholder: 'ძიება — № ან პროდუქტი',
    productSearch: 'პროდუქტის ძიება…',
    filterCats: { status: 'სტატუსი', product: 'პროდუქტი', period: 'პერიოდი' },
    cols: {
      number: 'კონტრაქტის №',
      product: 'პროდუქტი',
      start: 'დაწყება',
      end: 'დასრულება',
      insured: 'დაზღვეული',
      status: 'სტატუსი',
    },
    status: { active: 'აქტიური', ended: 'დასრულებული' },
    newContract: 'ახალი კონტრაქტი',
    actions: {
      menu: 'მოქმედებები',
      details: 'დეტალურად',
      viewPolicies: 'პოლისების ნახვა',
    },
    emptyTitle: 'კონტრაქტი ვერ მოიძებნა',
    emptyHint: 'შეცვალეთ ან გაასუფთავეთ ფილტრები და ძიება',
    emptyAction: 'ყველას ჩვენება',
    /* Contract-details drawer (shared Drawer shell, 2026-07-16). Title is
       GENERIC on purpose — every detail drawer reads "<record> დეტალები" and
       record identity lives in the body, unifying the drawer experience. */
    drawer: {
      title: 'კონტრაქტის დეტალები',
      name: 'დასახელება',
      number: 'კონტრაქტის №',
      period: 'პერიოდი',
      insured: 'დაზღვეული',
      premium: 'წლიური პრემია',
      schedule: 'გადახდის გრაფიკი',
      included: 'რა შედის კონტრაქტში',
      documents: 'დოკუმენტები',
      contractPdf: 'კონტრაქტი (PDF)',
      download: 'ჩამოტვირთვა',
      close: 'დახურვა',
    },
  },
  /* Invoices — the finances index (concept agreed 2026-07-20). */
  invoices: {
    subtitle: (n, overdue) => `${n} ინვოისი · ${overdue} ვადაგადაცილებული`,
    summary: {
      overdue: 'ვადაგადაცილებული',
      due: 'გადასახდელი',
      paidYtd: 'გადახდილი (წელს)',
      invoicesN: (n) => `${n} ინვოისი`,
      nextDue: (d) => `მომდევნო ვადა ${d}`,
      none: 'ყველა გადახდილია',
    },
    filterCats: { status: 'სტატუსი', product: 'პროდუქტი', contract: 'კონტრაქტი', period: 'პერიოდი' },
    searchPlaceholder: 'ძიება — ინვოისის № ან კონტრაქტი',
    productSearch: 'პროდუქტის ძიება…',
    cols: {
      invoice: 'ინვოისი',
      subject: 'კონტრაქტი / პერიოდი',
      due: 'გადახდის ვადა',
      amount: 'თანხა',
      status: 'სტატუსი',
    },
    status: { overdue: 'ვადაგადაცილებული', due: 'გადასახდელი', paid: 'გადახდილი', credited: 'გაუქმებული' },
    rel: {
      overdue: (n) => `${n} დღით ვადაგადაცილ.`,
      due: (n) => `${n} დღეში`,
      paid: 'გადახდილი',
    },
    actions: { menu: 'მოქმედებები', details: 'დეტალურად', pay: 'გადახდა', pdf: 'PDF-ის ჩამოტვირთვა' },
    /* Invoice-details drawer — shares the contract-drawer language + adds an
       amount hero and a "what it covers" breakdown. */
    drawer: {
      title: 'ინვოისის დეტალები',
      amountDue: 'გადასახდელი თანხა',
      amountPaid: 'გადახდილი თანხა',
      dueOverdue: (d, n) => `ვადა ${d} · ${n} დღით ვადაგადაცილებული`,
      dueSoon: (d, n) => `ვადა ${d} · ${n} დღეში`,
      paidOn: (d) => `გადახდილია ${d}`,
      canceled: 'გაუქმებული ინვოისი',
      contract: 'კონტრაქტი',
      product: 'პროდუქტი',
      period: 'პერიოდი',
      issued: 'გამოწერის თარიღი',
      due: 'გადახდის ვადა',
      paidDate: 'გადახდის თარიღი',
      breakdown: 'რას მოიცავს',
      illustrative: '(საილუსტრაციო)',
      colItem: 'პოზიცია',
      colQty: 'რაოდ.',
      colAmount: 'თანხა',
      total: 'სულ',
      documents: 'დოკუმენტები',
      invoicePdf: 'ინვოისი (PDF)',
      download: 'ჩამოტვირთვა',
      close: 'დახურვა',
    },
    emptyTitle: 'ინვოისი ვერ მოიძებნა',
    emptyHint: 'შეცვალეთ ან გაასუფთავეთ ფილტრები და ძიება',
    emptyAction: 'ყველას ჩვენება',
  },
  /* Statement — read-only per-insured premium ledger (concept agreed 2026-07-20). */
  statement: {
    subtitle: (n) => `${n} ჩანაწერი · პრემიის განაწილება (კომპანია / თანამშრომელი) · მხოლოდ ჯანმრთელობა`,
    filterCats: { period: 'პერიოდი', contract: 'კონტრაქტი', package: 'პაკეტი', status: 'სტატუსი' },
    searchPlaceholder: 'ძიება — სახელი, პირადი № ან კონტრაქტი',
    cols: {
      insured: 'დაზღვეული',
      pid: 'პირადი №',
      contract: 'კონტრაქტი №',
      package: 'პაკეტი',
      period: 'პერიოდი',
      premium: '₾ / თვე',
      paid: 'გადახდილი',
      companyPct: 'კომპ. %',
      companyGel: 'კომპ. ₾',
      employeePct: 'თანამშ. %',
      employeeGel: 'თანამშ. ₾',
      status: 'სტატუსი',
    },
    status: { paid: 'გადახდილი', due: 'გადასახდელი' },
    emptyTitle: 'ჩანაწერი ვერ მოიძებნა',
    emptyHint: 'შეცვალეთ ან გაასუფთავეთ ფილტრები და ძიება',
    emptyAction: 'ყველას ჩვენება',
  },
  addIns: {
    title: 'დაზღვეულის დამატება',
    crumbParent: 'პოლისები',
    cancel: 'გაუქმება',
    cancelConfirm: 'შეყვანილი მონაცემები დაიკარგება. დატოვებთ გვერდს?',
    steps: { method: 'მეთოდი', data: 'მონაცემები', review: 'გადახედვა' },
    contractLabel: 'კონტრაქტი',
    contractChange: 'შეცვლა',
    contractSingle: 'ერთი აქტიური კონტრაქტი',
    method: {
      heading: 'როგორ გსურთ თანამშრომლების დამატება?',
      single: { title: 'ერთი პირის დამატება', meta: 'ფორმით — ოჯახის წევრებთან ერთად' },
      excel: { title: 'Excel ატვირთვა', meta: 'სტანდარტული შაბლონი · ვალიდაცია' },
      link: { title: 'ბმულის გაგზავნა', meta: 'თანამშრომლები თავად შეავსებენ ფორმას' },
      hr: { title: 'HR სისტემიდან', meta: 'BambooHR, API ინტეგრაცია' },
      later: 'მოგვიანებით',
      soon: 'მალე',
      headcount: 'გჭირდებათ ჯამური რაოდენობის შემოწმება?',
      headcountBody: 'შეადარეთ შემოსავლების სამსახურის მონაცემებს — დარწმუნდით, რომ არავინ გამოგრჩათ.',
    },
    /* Excel import (step 2, Excel mode). Count-interpolating strings are arrow
       functions, matching this file's convention. Georgian nouns do not inflect
       after numerals, so `${n} სტრიქონი` is correct for every n — no plural
       helper. No Georgian ordinals anywhere: the formation is irregular
       (პირველ / მეორე / მესამე / მე-N) and a naive template produces wrong
       Georgian. */
    excel: {
      heading: 'ატვირთეთ თანამშრომლების სია',
      step1: 'ჩამოტვირთეთ შაბლონი',
      step1Body: 'შაბლონში სვეტები და პაკეტების სახელები უკვე ჩაწერილია — არ შეცვალოთ სათაურების სტრიქონი.',
      download: 'შაბლონის ჩამოტვირთვა (.xlsx)',
      step2: 'ატვირთეთ შევსებული ფაილი',
      step2Body: 'ერთ ფაილში შეგიძლიათ როგორც თანამშრომლები, ისე ოჯახის წევრები.',
      dropTitle: 'გადმოათრიეთ ფაილი აქ',
      dropBrowse: 'აირჩიეთ ფაილი',
      dropReplace: 'სხვა ფაილის არჩევა',
      dropReqs: '.xlsx · მაქსიმუმ 5 MB · მაქსიმუმ 500 სტრიქონი',
      dropHint: 'ოჯახის წევრი დაუკავშირეთ თანამშრომელს პირადი ნომრით.',
      clearFile: 'ფაილის მოხსნა',
      tipTitle: 'რჩევა',
      tipBody: 'პირადი ნომრის სვეტი Excel-ში ტექსტად დატოვეთ — წინააღმდეგ შემთხვევაში პირველი ნული იკარგება.',

      validating: 'მიმდინარეობს შემოწმება…',

      readSummary: (sheet, rows) => `წავიკითხეთ ფურცელი „${sheet}" · ${rows} სტრიქონი`,
      replaceFile: 'ფაილის შეცვლა',
      replaceTitle: 'ახალი ფაილის ატვირთვა?',
      replaceBody: 'ამ ფაილში შეტანილი შესწორებები და წაშლილი სტრიქონები დაიკარგება.',
      replaceYes: 'ატვირთვა',
      replaceKeep: 'დატოვება',
      switchConfirm: 'მეთოდის შეცვლისას შეყვანილი მონაცემები დაიკარგება. გავაგრძელოთ?',
      tableCaption: 'ატვირთული ფაილის სტრიქონები',
      filterLabel: 'სტრიქონების ფილტრი',
      ledger: (send, removed) => `გასაგზავნი: ${send} · წაშლილი: ${removed}`,

      stats: {
        total: 'სულ სტრიქონი',
        ready: 'გასაგზავნი',
        errors: 'შეცდომა',
        premium: 'ჯამური პრემია',
      },
      filters: {
        all: 'ყველა',
        errors: 'შეცდომით',
        warnings: 'გაფრთხილებით',
        exists: 'უკვე დაზღვეული',
        ready: 'მზადაა',
      },
      status: {
        ready: 'მზადაა',
        warning: 'გაფრთხილება',
        error: 'შეცდომა',
      },
      cols: {
        row: 'სტრ. №',
        name: 'სახელი გვარი',
        pid: 'პირადი №',
        birth: 'დაბ. თარიღი',
        package: 'პაკეტი',
        status: 'სტატუსი',
        issues: 'შენიშვნა',
      },

      rowRemove: 'სტრიქონის წაშლა',
      rowRestore: 'დაბრუნება',
      removeAllErrors: (n) => `ყველა შეცდომიანის წაშლა (${n})`,
      removedTray: (n) => `წაშლილი სტრიქონები (${n})`,
      removedShow: 'ჩვენება',
      removedHide: 'დამალვა',
      removedNote: 'წაშლილი სტრიქონები არ გაიგზავნება — მათი ცალკე ატვირთვა მოგვიანებით შეგიძლიათ.',

      emptyFilterTitle: 'ამ ფილტრში სტრიქონი აღარ არის',
      emptyFilterHint: 'ყველა შესწორდა ან წაიშალა.',
      emptyFilterAction: 'ყველას ჩვენება',

      blockTitle: (n) => `${n} სტრიქონში შეცდომაა`,
      blockBody: 'გაგზავნამდე თითოეული სტრიქონი უნდა გაასწოროთ ან წაშალოთ.',
      allClearTitle: 'ყველა სტრიქონი გამართულია',
      allClearBody: (n, sum) => `${n} პირი მზადაა გასაგზავნად · ${sum} / თვე`,
      continueDisabled: (n) => `ჯერ გაასწორეთ ან წაშალეთ ${n} სტრიქონი`,
      continueEmpty: 'ატვირთეთ შევსებული ფაილი',

      drawer: {
        title: 'სტრიქონის გასწორება',
        close: 'დახურვა',
        next: 'შემდეგი შეცდომა',
        issuesTitle: 'რა უნდა გასწორდეს',
      },

      live: {
        selected: (name, size) => `ფაილი არჩეულია: ${name}, ${size}. მიმდინარეობს შემოწმება…`,
        doneClean: (n) => `შემოწმება დასრულდა. ${n} სტრიქონი მზადაა შეცდომების გარეშე.`,
        doneMixed: (total, ok, err, warn) =>
          `შემოწმება დასრულდა. ${total} სტრიქონი: ${ok} მზადაა, ${err} შეცდომა, ${warn} გაფრთხილება. სია გაფილტრულია შეცდომიან სტრიქონებზე.`,
        doneNone: (err) => `შემოწმება დასრულდა. ვერცერთი სტრიქონი ვერ დაემატება — ${err} შეცდომა.`,
        removed: (n) => `${n} სტრიქონი ამოღებულია. დაბრუნება შესაძლებელია წაშლილების სიიდან.`,
        removedCascade: (n, fam) => `${n} სტრიქონი ამოღებულია, მათ შორის ${fam} დაკავშირებული ოჯახის წევრი.`,
        restored: (n) => `${n} სტრიქონი დაბრუნებულია.`,
        filtered: (n) => `ნაჩვენებია ${n} სტრიქონი.`,
      },

      fileErr: {
        type: 'ფაილის ფორმატი არ არის მხარდაჭერილი. ატვირთეთ .xlsx ფაილი.',
        xls: 'ძველი ფორმატი (.xls). გახსენით Excel-ში და შეინახეთ როგორც .xlsx.',
        csv: 'CSV ფაილში ქართული ასოები ზიანდება. გახსენით Excel-ში და შეინახეთ როგორც .xlsx.',
        size: (mb, max) => `ფაილის ზომაა ${mb} MB — მაქსიმუმ ${max} MB.`,
        unreadable:
          'ფაილი ვერ წავიკითხეთ — შესაძლოა დაზიანებულია ან პაროლითაა დაცული. მოხსენით დაცვა, შეინახეთ ხელახლა .xlsx ფორმატში და სცადეთ თავიდან.',
        empty: 'ფაილი ცარიელია — შევსებული სტრიქონი ვერ ვიპოვეთ. შეავსეთ შაბლონი და ხელახლა ატვირთეთ.',
        wrongTemplate: (cols) =>
          `ეს GPI-ის შაბლონი არ არის — ვერ ვიპოვეთ სვეტები: ${cols}. ჩამოტვირთეთ შაბლონი და მონაცემები მასში გადაიტანეთ.`,
        headers: (cols) => `ვერ მოიძებნა სავალდებულო სვეტი: ${cols}. სვეტის სახელი ზუსტად უნდა ემთხვეოდეს შაბლონს.`,
        headerDup: (h) => `სვეტი „${h}" ორჯერაა — წაშალეთ დუბლიკატი და ხელახლა ატვირთეთ.`,
        tooManyRows: (n, max) =>
          `ფაილში ${n} სტრიქონია — მაქსიმუმ ${max}. დაყავით რამდენიმე ფაილად და ატვირთეთ ცალ-ცალკე.`,
      },

      notice: {
        multiSheet: (n, name) => `ფაილში ${n} ფურცელია — წავიკითხეთ მხოლოდ „${name}"`,
        extraCols: (cols) => `დამატებითი სვეტები არ გავითვალისწინეთ: ${cols}`,
        skippedEmpty: (n) => `${n} ცარიელი სტრიქონი გამოვტოვეთ`,
      },

      err: {
        who: (v) => `უცნობი ტიპი „${v}". დასაშვებია: თანამშრომელი, ოჯახის წევრი.`,
        whoInferred: 'ტიპი ცარიელია — ჩაითვალა „ოჯახის წევრად".',
        citizen: (v) => `უცნობი მოქალაქეობა „${v}" — ჩაითვალა „საქართველოს მოქალაქედ".`,
        pidLeadingZero: (pid) => `პირად ნომერს დაემატა წინა ნული — გადაამოწმეთ: ${pid}`,
        pidNonResident: 'არარეზიდენტის დოკუმენტის ნომერი უნდა შედგებოდეს 5–20 ასო-ციფრისგან.',
        date: 'თარიღი ჩაწერეთ ფორმატით დდ/თთ/წწწწ — მაგ. 05/03/1990.',
        dateInvalid: 'ასეთი თარიღი არ არსებობს — გადაამოწმეთ.',
        dateFuture: 'დაბადების თარიღი მომავალშია — გადაამოწმეთ.',
        dateOdd: 'დაბადების თარიღი უჩვეულოა — გადაამოწმეთ.',
        minorEmployee: 'თანამშრომელი 16 წელზე ნაკლებია — გადაამოწმეთ.',
        gender: (v) => `უცნობი მნიშვნელობა „${v}". დასაშვებია: მამრობითი, მდედრობითი.`,
        package: (v, list) => `უცნობი პაკეტი „${v}". დასაშვებია: ${list}.`,
        relation: (v, list) => `უცნობი კავშირი „${v}". დასაშვებია: ${list}.`,
        relationIgnored: 'თანამშრომელს კავშირი არ სჭირდება — ეს უჯრა არ გავითვალისწინეთ.',
        linkMissing: 'ოჯახის წევრს უნდა მიეთითოს თანამშრომლის პირადი ნომერი.',
        linkNotFound: (pid) => `თანამშრომელი პირადი ნომრით ${pid} ვერ მოიძებნა — ვერც ფაილში და ვერც უკვე დაზღვეულებში.`,
        linkSelf: 'პირი საკუთარ თავს ვერ დაუკავშირდება.',
        linkIsFamily: 'ბმა უნდა მიუთითებდეს თანამშრომელზე, არა ოჯახის წევრზე.',
        linkCascade: (n) => `დაკავშირებულ თანამშრომელს (სტრ. № ${n}) აქვს შეცდომა — ჯერ ის გაასწორეთ.`,
        dupInFile: (row) => `პირადი ნომერი ფაილში მეორდება (სტრ. № ${row}) — დატოვეთ ერთი.`,
        email: 'ელ-ფოსტის ფორმატი საეჭვოა — გადაამოწმეთ.',
        mobile: 'მობილურის ფორმატი საეჭვოა — მაგ. +995 5XX XXX XXX.',
      },

      exists: {
        label: 'უკვე დაზღვეულია',
        body: 'ეს პირი უკვე დაზღვეულია ამ კონტრაქტით — ხელახლა არ დაემატება.',
      },
    },
    who: {
      label: 'ვის ამატებთ?',
      employee: 'თანამშრომელი',
      employeeMeta: 'კომპანიის დასაქმებული',
      family: 'ოჯახის წევრი',
      familyMeta: 'თანამშრომელთან დაკავშირებული პირი',
    },
    form: {
      citizen: 'მოქალაქეობა',
      resident: 'საქართველოს მოქალაქე',
      nonresident: 'არარეზიდენტი',
      personalId: 'პირადი ნომერი',
      personalIdPh: 'მაგ. 01001001234',
      birthDate: 'დაბადების თარიღი',
      birthDatePh: 'დდ/თთ/წწწწ',
      found: 'მოიძებნა შემოსავლების სამსახურში',
      notFound: 'ამ მონაცემებით პირი ვერ მოიძებნა — შეავსეთ ველები ხელით.',
      firstName: 'სახელი',
      lastName: 'გვარი',
      gender: 'სქესი',
      genderPh: 'აირჩიეთ',
      male: 'მამრობითი',
      female: 'მდედრობითი',
      linkedTo: 'თანამშრომელი (ბმა)',
      linkedToPh: 'აირჩიეთ თანამშრომელი',
      linkedNew: 'ახალი:',
      relation: 'კავშირი',
      relationPh: 'აირჩიეთ კავშირი',
      mobile: 'მობილური',
      mobilePh: '+995 5XX XXX XXX',
      email: 'ელ-ფოსტა',
      emailPh: 'name@mail.ge',
      address: 'მისამართი',
      addressPh: 'ქ. თბილისი, ...',
      package: 'სადაზღვევო პაკეტი',
      packagePh: 'აირჩიეთ პაკეტი',
      policyType: 'პოლისის ტიპი',
      premium: 'ყოველთვიური პრემია',
      systemTag: 'სისტემიდან',
      policyTypeValue: 'ჯანმრთ. CORPO Standard',
      addToList: 'სიაში დამატება',
      updateInList: 'განახლება',
      clearForm: 'გასუფთავება',
      errRequired: 'სავალდებულო ველი',
      errPid: 'პირადი ნომერი უნდა შედგებოდეს 11 ციფრისგან.',
    },
    batch: {
      heading: 'სიაშია',
      empty: 'ჯერ არავინ დაგიმატებიათ — შეავსეთ ფორმა და დაამატეთ სიაში.',
      addFamily: 'ოჯახის წევრი',
      edit: 'რედაქტირება',
      remove: 'წაშლა',
      employeeTag: 'თანამშრომელი',
      perMonth: '₾/თვე',
    },
    side: {
      rulesTitle: 'კონტრაქტის წესები',
      rulesAuto: 'აქტიურდება ავტომატურად',
      ruleWindowTitle: 'დამატების ფანჯარა',
      ruleWindow: 'ყოველი თვის 1–25 რიცხვი',
      rulePackageTitle: 'პაკეტი',
      rulePackage: 'კონტრაქტიდან 3 თვის შემდეგ ახალი პირისთვის — მხოლოდ „ბაზისი"',
      ruleWaitTitle: 'ლოდინის პერიოდი',
      ruleWait: 'ორსულობა / მშობიარობა — 9 თვე',
      nextTitle: 'რა მოხდება შემდეგ',
      nextBody: 'ავტო-ვალიდაცია → GPI ბექ-ოფისი (≤ 24 სთ) → შეტყობინება',
      bulkTip: '10+ პირი? დაბრუნდით პირველ ნაბიჯზე და აირჩიეთ „Excel ატვირთვა".',
    },
    review: {
      heading: 'გადახედეთ და გააგზავნეთ',
      people: 'პირი',
      total: 'ჯამი',
      totalNote: 'დაემატება მომდევნო ინვოისს',
      submit: 'მოთხოვნის გაგზავნა',
    },
    done: {
      title: 'მოთხოვნა შეიქმნა',
      requestNo: 'მოთხოვნა #43512',
      status: 'დამუშავების პროცესში',
      meta: 'პასუხი ≤ 24 საათში — მიიღებთ შეტყობინებას',
      viewRequest: 'მოთხოვნის ნახვა',
      addMore: 'კიდევ დამატება',
      home: 'მთავარი გვერდი',
    },
  },
  pages: {
    home: { title: 'მთავარი გვერდი', subtitle: 'მიმოხილვა და შეხსენებები' },
    contracts: { title: 'კონტრაქტები' },
    requests: { title: 'მოთხოვნები', subtitle: '7 მიმდინარე მოთხოვნა' },
    claims: { title: 'ზარალები', subtitle: '3 ელოდება თქვენს დადასტურებას' },
    invoices: { title: 'ინვოისები', subtitle: '1 ვადაგადაცილებული · ₾ 6,450' },
    statement: { title: 'ამონაწერი', subtitle: 'პრემიის განაწილება — კომპანია / თანამშრომელი' },
    guide: { title: 'გზამკვლევი', subtitle: 'ვიდეოები, FAQ და სახელმძღვანელოები თანამშრომლებისთვის' },
    offers: { title: 'შეთავაზებები', subtitle: 'შეთავაზებები კომპანიისა და თანამშრომლებისთვის' },
    adminUsers: { title: 'მომხმარებლები და როლები', subtitle: 'წვდომის მართვა' },
    adminOrg: { title: 'ორგანიზაცია', subtitle: 'კომპანიის მონაცემები' },
  },
}
